export const animals = [
  {label: "Times New Roman", value: "Times New Roman"},
  {label: "Futura", value: "Futura"},
  {label: "Arial", value: "Arial"},
  {label: "Helvetica", value: "Helvetica"},
  {label: "Calibri", value: "Calibri"},
  {label: "Verdana", value: "Verdana"},
  {label: "Inter", value: "Inter"},
  {label: "Caslon", value: "Caslon"},
  {label: "Garamond", value: "Garamond"},
  {label: "Georgia", value: "Georgia"},
  {label: "Comic Sans", value: "Comic Sans"},
  {label: "Consolas", value: "Consolas"},
  {label: "Tahoma", value: "Tahoma"},
  {label: "Freestyle Script", value: "Freestyle Script"},
  {label: "Lucida Calligraphy", value: "Lucida Calligraphy"},
  {label: "Mistral", value: "Mistral"},
  {label: "Segoe Script", value: "Segoe Script"},
  {label: "Cookie", value: "Cookie"},
  {label: "Allura", value: "Allura"},
  {label: "Tilda Sans", value: "Tilda Sans"},
  {label: "Patrick Hand", value: "Patrick Hand"},
  {label: "Pacifico", value: "Pacifico"},
  {label: "Chalkduster", value: "Chalkduster"},
  {label: "Lobster", value: "Lobster"},
  {label: "Quicksand", value: "Quicksand"},
  {label: "Yellowtail", value: "Yellowtail"},
  {label: "Avenir", value: "Avenir"},
  {label: "Cochin", value: "Cochin"},
  {label: "Didot", value: "Didot"},
  {label: "Woodchuck", value: "Woodchuck"},
  {label: "Boom Comic Font", value: "Boom Comic Font"},
  {label: "Nikopol Typeface", value: "Nikopol Typeface"},
  {label: "Badaboom", value: "Badaboom"},
  {label: "Komika", value: "Komika"},
  {label: "Adam Warren Pro", value: "Adam Warren Pro"},
  {label: "Reality Check", value: "Reality Check"},
  {label: "Hey Comic", value: "Hey Comic"},
  {label: "Fanboy Hardcore", value: "Fanboy Hardcore"},
  {label: "Komika Title", value: "Komika Title"}
];